-- Student Management System - Database Schema
-- Run this in your Supabase SQL Editor

-- 1. Update Profiles table (extends auth.users OR standalone)
-- If using Supabase Auth:
-- CREATE TABLE profiles (
--   id UUID REFERENCES auth.users ON DELETE CASCADE PRIMARY KEY,
-- If standalone:
CREATE TABLE IF NOT EXISTS profiles (
    id UUID PRIMARY KEY,
    full_name TEXT,
    email TEXT UNIQUE NOT NULL,
    password TEXT NOT NULL,
    roll_no TEXT,
    branch TEXT,
    role TEXT CHECK (role IN ('STUDENT', 'ADMIN')) DEFAULT 'STUDENT',
    profile_picture TEXT,
    contact_info TEXT,
    is_deleted BOOLEAN DEFAULT FALSE,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- 2. Courses
CREATE TABLE IF NOT EXISTS courses (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    course_code TEXT UNIQUE,
    course_name TEXT,
    credits INT,
    teacher_name TEXT,
    description TEXT
);

-- 3. Enrollments (Junction Table)
CREATE TABLE IF NOT EXISTS enrollments (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    student_id UUID REFERENCES profiles(id),
    course_id BIGINT REFERENCES courses(id),
    enrolled_at TIMESTAMP DEFAULT NOW(),
    grade TEXT,
    marks DOUBLE PRECISION,
    gpa DOUBLE PRECISION
);

-- 4. Attendance
CREATE TABLE IF NOT EXISTS attendance (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    student_id UUID REFERENCES profiles(id),
    course_id BIGINT REFERENCES courses(id),
    date DATE NOT NULL,
    status TEXT CHECK (status IN ('PRESENT', 'ABSENT'))
);

-- Create indexes for performance
CREATE INDEX IF NOT EXISTS idx_enrollments_student ON enrollments(student_id);
CREATE INDEX IF NOT EXISTS idx_enrollments_course ON enrollments(course_id);
CREATE INDEX IF NOT EXISTS idx_attendance_student ON attendance(student_id);
CREATE INDEX IF NOT EXISTS idx_attendance_date ON attendance(date);

-- Insert a default admin user (password: admin123)
-- BCrypt hash for 'admin123': $2a$10$N9qo8uLOickgx2ZMRZoMy.MqrqhAIKxJl/OJP.QWHQKMKuVv.z/JW
INSERT INTO profiles (id, full_name, email, password, role, is_deleted)
VALUES (
    'a0eebc99-9c0b-4ef8-bb6d-6bb9bd380a11',
    'System Admin',
    'admin@school.edu',
    '$2a$10$N9qo8uLOickgx2ZMRZoMy.MqrqhAIKxJl/OJP.QWHQKMKuVv.z/JW',
    'ADMIN',
    false
) ON CONFLICT (email) DO NOTHING;

-- Insert sample courses
INSERT INTO courses (course_code, course_name, credits, teacher_name, description)
VALUES 
    ('CS101', 'Introduction to Computer Science', 3, 'Dr. Smith', 'Fundamentals of programming'),
    ('MA101', 'Calculus I', 4, 'Prof. Johnson', 'Differential and integral calculus'),
    ('PH101', 'Physics I', 3, 'Dr. Williams', 'Mechanics and thermodynamics')
ON CONFLICT (course_code) DO NOTHING;
